const cmcCoinMap: { [krakenCoinName: string]: string; } = {
    "AAVE": "AAVE",
    "ADA.S": "ADA",
    "ALGO": "ALGO",
    "ALGO.S": "ALGO",
    "ATOM": "ATOM",
    "BCH": "BCH",
    "DOT.S": "DOT",
    "ETH2": "ETH",
    "ETH2.S": "ETH",
    "LINK": "LINK",
    "LRC": "LRC",
    "MATIC": "MATIC",
    "SOL": "SOL",
    "SOL.S": "SOL",
    "USD.M": "ZUSD",
    "USDC": "USDC",
    "XBT.M": "BTC",
    "XETH": "ETH",
    "XLTC": "LTC",
    "XTZ": "XTZ",
    "XXBT": "BTC",
    "XXDG": "DOGE",
    "XXLM": "XLM",
    "XXMR": "XMR",
    "XXRP": "XRP",
    "ZUSD": "ZUSD",
};

export default cmcCoinMap;
