import CoinId from "../CoinId";

const marketCoinMap: { [krakenCoinName: string]: CoinId; } = {
    // "AAVE": "aave",
    // "ADA.S": "cardano",
    // "ALGO": "algorand",
    // "ALGO.S": "algorand",
    // "ATOM": "cosmos",
    // "BCH": "bitcoin-cash",
    // "DOT.S": "polkadot",
    // "ETH2": "ethereum",
    // "ETH2.S": "ethereum",
    // "LINK": "chainlink",
    // "LRC": "loopring",
    // "MATIC": "matic-network",
    // "SOL": "solana",
    // "SOL.S": "solana",
    // "USD.M": "zusd",
    // "USDC": "usd-coin",
    // "XBT.M": "bitcoin",
    // "XETH": "ethereum",
    // "XLTC": "litecoin",
    // "XTZ": "tezos",
    // "XXBT": "bitcoin",
    // "XXDG": "dogecoin",
    // "XXLM": "stellar",
    // "XXMR": "monero",
    // "XXRP": "ripple",
    // "ZUSD": "zusd",
    "AAVE": CoinId.AAVE,
    "ADA.S": CoinId.ADA,
    "ALGO": CoinId.ALGO,
    "ALGO.S": CoinId.ALGO,
    "ATOM": CoinId.ATOM,
    "BCH": CoinId.BCH,
    "DOT.S": CoinId.DOT,
    "ETH2": CoinId.ETH,
    "ETH2.S": CoinId.ETH,
    "LINK": CoinId.LINK,
    "LRC": CoinId.LRC,
    "MATIC": CoinId.MATIC,
    "SOL": CoinId.SOL,
    "SOL.S": CoinId.SOL,
    "USD.M": CoinId.ZUSD,
    "USDC": CoinId.USDC,
    "XBT.M": CoinId.BTC,
    "XETH": CoinId.ETH,
    "XLTC": CoinId.LTC,
    "XTZ": CoinId.XTZ,
    "XXBT": CoinId.BTC,
    "XXDG": CoinId.DOGE,
    "XXLM": CoinId.XLM,
    "XXMR": CoinId.XMR,
    "XXRP": CoinId.XRP,
    "ZUSD": CoinId.ZUSD,
};

export default marketCoinMap;
