const marketCoinMap: { [krakenCoinName: string]: string; } = {
    "AAVE": "aave",
    "ADA.S": "cardano",
    "ALGO": "algorand",
    "ALGO.S": "algorand",
    "ATOM": "cosmos",
    "BCH": "bitcoin-cash",
    "DOT.S": "polkadot",
    "ETH2": "ethereum",
    "ETH2.S": "ethereum",
    "LINK": "chainlink",
    "LRC": "loopring",
    "MATIC": "matic-network",
    "SOL": "solana",
    "SOL.S": "solana",
    "USD.M": "zusd",
    "USDC": "usd-coin",
    "XBT.M": "bitcoin",
    "XETH": "ethereum",
    "XLTC": "litecoin",
    "XTZ": "tezos",
    "XXBT": "bitcoin",
    "XXDG": "dogecoin",
    "XXLM": "stellar",
    "XXMR": "monero",
    "XXRP": "ripple",
    "ZUSD": "zusd",
};

export default marketCoinMap;
